#!/bin/bash
set -e

function getJsonVal () {
  python -c "import json,sys;sys.stdout.write(json.dumps(json.load(sys.stdin)$1, sort_keys=True, indent=4))";
}

url=https://tutorial.cloudflareworkers.com
url=${1:-$url}

id=$(curl 'https://cloudflareworkers.com/script' -H 'pragma: no-cache' -H 'origin: https://cloudflareworkers.com' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'content-type: text/javascript; charset=UTF-8' -H 'accept: */*' -H 'cache-control: no-cache' -H 'authority: cloudflareworkers.com' -H 'referer: https://cloudflareworkers.com/' --compressed --data-binary @- <&0 |  getJsonVal "['id']")
id="${id%\"}"
id="${id#\"}"

open "https://cloudflareworkers.com/#$id:$url"
